import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Footer from './components/footer/footer'
import NavBar from './components/nav/navBar'

const poppins = Poppins({ subsets: ['latin-ext'], display: 'swap', weight: ["400", "700"] })

export const metadata: Metadata = {
  title: 'Hamilton Market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/*children are the website's webpages*/}
      <body className={`${poppins.className} text-slate-700`}>
        <div className='flex flex-col min-h-screen'>
          <NavBar></NavBar>
          <main className='flex-grow'>{children}</main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  )
}
